### ISSUE TITLE
Nelze nahrat produkt z produkce

### ISSUE THREAD

**Issue by rojcyk** [rojcyk/rojcyk-app#22]
```Feb 28 00:30:58 rojcyk-app app/web.1:  2017-02-28 08:30:57 - NoMethodError - undefined method `object' for nil:NilClass: 
Feb 28 00:30:58 rojcyk-app app/web.1:  	/app/models/asset.rb:140:in `s3_object' 
Feb 28 00:30:58 rojcyk-app app/web.1:  	/app/models/asset.rb:181:in `presigned_post' 
Feb 28 00:30:58 rojcyk-app app/web.1:  	/app/modules/admin/products_module.rb:199:in `block in <class:ProductsModule>' 
Feb 28 00:30:58 rojcyk-app app/web.1:  	/app/vendor/bundle/ruby/2.4.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1611:in `call' 
Feb 28 00:30:58 rojcyk-app app/web.1:  	/app/vendor/bundle/ruby/2.4.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1611:in `block in compile!' 
Feb 28 00:30:58 rojcyk-app app/web.1:  	/app/vendor/bundle/ruby/2.4.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:975:in `block (3 levels) in route!' 
Feb 28 00:30:58 rojcyk-app app/web.1:  	/app/vendor/bundle/ruby/2.4.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:994:in `route_eval' ```

produkt:

[blueprint-v4.zip](https://github.com/rojcyk/rojcyk-app/files/806114/blueprint-v4.zip)

**Comment by rojcyk** [comment]
Jsem vul, slo o credentials
